name: Playit RDP Tunnel

on:
  workflow_dispatch:

jobs:
  setup-rdp-tunnel:
    runs-on: windows-latest

    steps:
    # 1. Kiểm tra repository
    - name: Check out the repository
      uses: actions/checkout@v2

    # 2. Tải và cài đặt Playit
    - name: Download and Install Playit
      run: |
        Invoke-WebRequest -Uri "https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-windows-x86_64-signed.exe" -OutFile "$env:USERPROFILE\playit.exe"
        Start-Sleep -Seconds 5  # Give some time for the download to complete

    # 3. Cấu hình Remote Desktop (RDP)
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "p@ssw0rd!" -Force)

    # 4. Khôi phục dữ liệu từ Artifact (nếu có)
    - name: Restore Previous Data from Artifacts
      uses: actions/download-artifact@v3
      with:
        name: playit-data
        path: $env:USERPROFILE\playit-data
      continue-on-error: true  # Bỏ qua nếu không có artifact

    # 5. Khởi chạy Playit và thiết lập RDP Tunnel
    - name: Start Playit and Set Up RDP Tunnel
      env:
        PLAYIT_AUTH_KEY: ${{ secrets.PL }}
      run: |
        # Tạo thư mục lưu dữ liệu nếu chưa tồn tại
        if (!(Test-Path -Path "$env:USERPROFILE\playit-data")) {
          New-Item -ItemType Directory -Path "$env:USERPROFILE\playit-data"
        }
        Start-Process -FilePath "$env:USERPROFILE\playit.exe" -ArgumentList "--secret $env:PLAYIT_AUTH_KEY" -NoNewWindow -Wait
        Start-Process -FilePath "$env:USERPROFILE\playit.exe" -NoNewWindow

    # 6. Lưu dữ liệu hiện tại vào Artifact
    - name: Save Data to Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: playit-data
        path: $env:USERPROFILE\playit-data

    # 7. Giữ phiên làm việc hoạt động (tránh đóng workflow)
    - name: Keep the GitHub Action Runner Alive
      run: |
        Start-Sleep -Seconds 11800  # Adjust the duration based on your needs
